### ISSUE TITLE
Move to github.com/gdcc? Add to Dataverse API Guide?

### ISSUE THREAD

**Issue by pdurbin** [gdcc/Dataverse.jl#4]
Hi! I spotted your tweet at https://twitter.com/GaelForget/status/1537033362543616005 

@poikilotherm and I would like to invite you to move this repo to the @gdcc GitHub org, next to pyDataverse: https://github.com/gdcc/pyDataverse

Totally up to you, of course! 😄 

Say the word and we'll create an empty repo, made you admin, etc. Thanks!

(Also, just to foreshadow a future step, we'd also love a pull request to update a future version of https://guides.dataverse.org/en/5.11/api/client-libraries.html to include Julia! Here's the source: https://github.com/IQSS/dataverse/blob/v5.11/doc/sphinx-guides/source/api/client-libraries.rst )

**Comment by gaelforget** [comment]
> Hi! I spotted your tweet at https://twitter.com/GaelForget/status/1537033362543616005
> 
> @poikilotherm and I would like to invite you to move this repo to the @gdcc GitHub org, next to pyDataverse: https://github.com/gdcc/pyDataverse
> 
> Totally up to you, of course! 😄
> 
> Say the word and we'll create an empty repo, made you admin, etc. Thanks!

Thank you!! Sounds good to me -- absolutely! I am waiting on the package registration to go through ( https://github.com/JuliaRegistries/General/pull/62370 ) before going back to clean some things up. 

Next week maybe?

> (Also, just to foreshadow a future step, we'd also love a pull request to update a future version of https://guides.dataverse.org/en/5.11/api/client-libraries.html to include Julia! Here's the source: https://github.com/IQSS/dataverse/blob/v5.11/doc/sphinx-guides/source/api/client-libraries.rst )

Sure. Could do that just after my cleaning up & the migration if that would work.

**Comment by pdurbin** [comment]
@gaelforget hi! Just checking in. Even if the Julia bindings aren't complete, we're happy to include a link in the Dataverse API Guide. No rush. Just something to think about. 😄

**Comment by gaelforget** [comment]
> @gaelforget hi! Just checking in. Even if the Julia bindings aren't complete, we're happy to include a link in the Dataverse API Guide. No rush. Just something to think about. 😄

Thanks for the ping. Working on it now

**Comment by gaelforget** [comment]
> Say the word and we'll create an empty repo, made you admin, etc. Thanks!

Previously when I transferred repo ownership to an org on GitHub, I think that we proceeded by 

- creating a team on the org side for the repo owners
- adding the repo to the team / making team admin of repo
- inviting pkg dev to org member
- adding pkg dev to the team

That's what we do in [JuliaClimate](https://github.com/orgs/JuliaClimate/teams) and [MITgcm](https://github.com/orgs/MITgcm/teams) for example.

On the org side, only someone with sufficient / owner privileges can create teams and so on. Details may depend on how you have the org set up.

One advantage, as compared to creating a fresh repo, is that everything in the original repo carries over -- i.e., issues, discussions, settings, ci, docs, zenodo links, webhooks, tags, etc. If instead of using the GitHub transfer mechanism I just push the git history into a fresh repo then the rest is lost.

@pdurbin , could we do the transfer this way via the GitHub ownership transfer?

**Comment by gaelforget** [comment]
> (Also, just to foreshadow a future step, we'd also love a pull request to update a future version of https://guides.dataverse.org/en/5.11/api/client-libraries.html to include Julia! Here's the source: https://github.com/IQSS/dataverse/blob/v5.11/doc/sphinx-guides/source/api/client-libraries.rst )

Done. Please refer to https://github.com/IQSS/dataverse/pull/8991

**Comment by pdurbin** [comment]
@gaelforget thanks! You used the "closes" syntax so automation closed this issue. I guess you could re-open it since you said "closes in part". Exciting to have Juila support!

**Comment by poikilotherm** [comment]
I'd have all the necessary permissions to do this move. We should take a look at this next week. Are you with us on Matrix? (chat.dataverse.org) I'm on during usual CEST working hours and sometimes after.

**Comment by gaelforget** [comment]
> I'd have all the necessary permissions to do this move on `gdcc` side. We should take a look at this next week. Are you with us on Matrix? (chat.dataverse.org) I'm on during usual CEST working hours and sometimes after.

Sounds good. Will join Matrix and should have time next week

**Comment by pdurbin** [comment]
@gaelforget thanks for working on this today! 🎉
